apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

namespace: kafka-cost-control-app

patches:
  - path: aggregator.yaml
  - path: grafana.yaml
  - path: kafka-cost-control-ui.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: kafka-cost-control-secret
  envs:
  - .env
