kind: Kustomization
resources:
  - ../base

namespace: kafka-cost-control

patches:
  - path: aggregator.yaml
  - path: grafana.yaml
  - path: kafka-cost-control-ui.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: kafka-cost-control-secret
  envs:
  - .env
