apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kafka-connect
  template:
    metadata:
      labels:
        k8s-app: kafka-connect
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: kafka-connect
          image: spoud/kafka-cost-control-exploration-connect:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 500Mi
          env:
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: kafka-connect
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: kafka-cost-control-connect-group
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: org.apache.kafka.connect.storage.StringConverter
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
            - name: CONNECT_CONFIG_STORAGE_PARTITIONS
              value: "1"
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "3"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: kcc-exploration-connect-configs
            - name: CONNECT_OFFSET_STORAGE_PARTITIONS
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "3"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: kcc-exploration-connect-offsets
            - name: CONNECT_STATUS_STORAGE_PARTITIONS
              value: "1"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "3"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: kafka-cost-control-connect-status
            - name: CONNECT_KEY_CONVERTER
              value: org.apache.kafka.connect.storage.StringConverter
            - name: CONNECT_VALUE_CONVERTER
              value: org.apache.kafka.connect.json.JsonConverter
          envFrom:
            - secretRef:
                name: kafka-connect-secret
          ports:
            - containerPort: 8083
              name: http
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 60

---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kafka-connect
  name: kafka-connect-service
spec:
  ports:
    - port: 8083
      name: http
      targetPort: 8083
  selector:
    k8s-app: kafka-connect
