apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - aggregator.yaml
  - timescaledb.yaml
  - kafka-connect.yaml
  - grafana.yaml
  - kafka-cost-control-ui.yaml

generatorOptions:
  disableNameSuffixHash: true
