name: Build frontend

on:
  push:
    branches: [ master ]
    paths: ['frontend/**']
  pull_request:
    branches: [ master ]
    paths: ['frontend/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: frontend/
        run: npm install

      - name: Generate Graphql
        working-directory: frontend/
        run: npm run generate

      - name: Build
        working-directory: frontend/
        run: npm run build

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          push: true
          tags: spoud/kafka-cost-control-ui:latest
