name: Build Kafka connect

on:
  push:
    branches: [ master ]
    paths: ['kafka-connect/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: kafka-connect/
          push: true
          tags: spoud/kafka-cost-control-connect:latest
