name: GitHub Pages Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pdf_build: true
          asciidoctor_params: -r asciidoctor-diagram
          source_dir: docs/ # default is .
          post_build: 'find . -name "*.png" -name "*.svg" | xargs git add -f'
