name: GitHub Pages Publish

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  PLANTUML_URL: https://plantuml.collaud.me

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pdf_build: true
          asciidoctor_params: -r asciidoctor-plantuml
          source_dir: docs/ # default is .
