name: GitHub Pages + Helm Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important parameter

      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pre_build: |
            mv "$INPUT_SOURCE_DIR" /tmp/source
            mv "helm" /tmp/source/
            #Ignores directories . and .git
            find . -not -path './.git*' -not -name '.' -exec rm -rf {} \; || true
            mv /tmp/source/* .
            git add .
          pdf_build: true
          asciidoctor_params: -r asciidoctor-diagram
          source_dir: docs/ # default is .
          post_build: 'cp -R helm docs/; find . -name "*.svg" | xargs git add -f'

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
